[tools]
deno = "2"
elixir = "1.18.4-otp-28"
erlang = "28.0.2"
flutter = "3.35.4-stable"
flux2 = "2.7.2"
go = "1.25"
helm = "3.19.0"
kubectl = "1.34.1"
node = "24.10.0"
pnpm = "10.18.2"
python = "3.13"
uv = "0.9"
